#include "test.h"

TEST_BEGIN(glGetFloatv) {
	GLfloat value;
	glGetFloatv(GL_INVALID_ENUM, &value);
	TEST_ERROR(GL_INVALID_ENUM);

	glGetFloatv(GL_GENERATE_MIPMAP_HINT, NULL);
	TEST_ERROR(GL_INVALID_VALUE);

	glGetFloatv(GL_GENERATE_MIPMAP_HINT, &value);
	TEST_CHECK(value == GL_DONT_CARE);
	TEST_ERROR(GL_NO_ERROR);

	glHint(GL_GENERATE_MIPMAP_HINT, GL_NICEST);
	glGetFloatv(GL_GENERATE_MIPMAP_HINT, &value);
	TEST_CHECK(value == GL_NICEST);
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glGetIntegerv) {
	GLint value;
	glGetIntegerv(GL_INVALID_ENUM, &value);
	TEST_ERROR(GL_INVALID_ENUM);

	glGetIntegerv(GL_GENERATE_MIPMAP_HINT, NULL);
	TEST_ERROR(GL_INVALID_VALUE);

	glGetIntegerv(GL_GENERATE_MIPMAP_HINT, &value);
	TEST_CHECK(value == GL_DONT_CARE);
	TEST_ERROR(GL_NO_ERROR);

	glHint(GL_GENERATE_MIPMAP_HINT, GL_NICEST);
	glGetIntegerv(GL_GENERATE_MIPMAP_HINT, &value);
	TEST_CHECK(value == GL_NICEST);
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glGetBooleanv) {
	GLboolean value;
	glGetBooleanv(GL_INVALID_ENUM, &value);
	TEST_ERROR(GL_INVALID_ENUM);

	glGetBooleanv(GL_GENERATE_MIPMAP_HINT, NULL);
	TEST_ERROR(GL_INVALID_VALUE);

	glGetBooleanv(GL_GENERATE_MIPMAP_HINT, &value);
	TEST_CHECK(value == GL_TRUE);
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glGetString) {
	TEST_CHECK(glGetString(GL_INVALID_ENUM) == NULL);
	TEST_ERROR(GL_INVALID_ENUM);

	TEST_CHECK(glGetString(GL_VENDOR) != NULL);
	TEST_CHECK(glGetString(GL_RENDERER) != NULL);
	TEST_CHECK(glGetString(GL_VERSION) != NULL);
	TEST_CHECK(glGetString(GL_SHADING_LANGUAGE_VERSION) != NULL);
	TEST_CHECK(glGetString(GL_EXTENSIONS) != NULL);
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glFlush) {
	glFlush();
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glFinish) {
	glFinish();
	TEST_ERROR(GL_NO_ERROR);
} TEST_END

TEST_BEGIN(glHint) {
	glHint(GL_INVALID_ENUM, GL_DONT_CARE);
	TEST_ERROR(GL_INVALID_ENUM);

	glHint(GL_GENERATE_MIPMAP_HINT, GL_INVALID_ENUM);
	TEST_ERROR(GL_INVALID_ENUM);

	glHint(GL_GENERATE_MIPMAP_HINT, GL_NICEST);
	TEST_ERROR(GL_NO_ERROR);
} TEST_END